### ISSUE TITLE
Allow time unit on the m3 file to be something other than seconds

### ISSUE THREAD

**Issue by AWSisco** [erdc/inflow#6]
Specifying `output_time_units` of `'days since 2000-01-01 00:00:00'` still gives a time variable in seconds on the m3 file. See example below.

```
int time(time) ;
	time:long_name = "time" ;
	time:standard_name = "time" ;
	time:units = "days since 2000-01-01 00:00:00" ;
	time:axis = "T" ;
	time:calendar = "gregorian" ;
	time:bounds = "time_bnds" ;

data:

 time = 0, 86400, 172800, 259200, 345600, 432000, 518400, 604800, 691200 ;
```

The expected behavior for 01–09 Jan 2000 using `'days since 2000-01-01 00:00:00'` is:

```
data:

 time = 0, 1, 2, 3, 4, 5, 6, 7, 8 ;
```

**Comment by mgeheran** [comment]
Hello, @AWSisco. Thank you for posting this issue. Please let me know if the new branch `allow_variable_time_units` produces the expected behavior.

**Comment by AWSisco** [comment]
The `allow_variable_time_units` branch behaves as expected for the `time` variable. However, the `time_bnds` variable still needs to account for the change.

For example, daily data stored using `days` now shows:

```
data:

 time = 0, 1, 2, 3, 4, 5, 6, 7, 8 ;
```

but `time_bnds` is incorrectly written as:

```
data:

 time_bnds =
  0, 86400,
  1, 86401,
  2, 86402,
  3, 86403,
  4, 86404,
  5, 86405,
  6, 86406,
  7, 86407,
  8, 86408 ;
```

Even once that correction is made, I am having second thoughts about whether this functionality should be merged into `main`. I had forgotten that using an m3 file with units other than `seconds` requires modifying some of the RAPID source routines and recompiling. I personally have found this worthwhile for my own projects, but for general users, allowing variable time units on the `main` easily introduces conflicts with RAPID.
