### ISSUE TITLE
Some projected catchment shapefiles may lead to unexpected weight table output

### ISSUE THREAD

**Issue by AWSisco** [erdc/inflow#7]
An input catchment shapefile with a projection of `ESRI:102039` causes some entries in the weight table to incorrectly have `area_sqm` of `0.0`.

```
<Derived Projected CRS: ESRI:102039>
Name: USA_Contiguous_Albers_Equal_Area_Conic_USGS_version
Axis Info [cartesian]:
- [east]: Easting (metre)
- [north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Albers Equal Area
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich
```

This could be related to the `catchment_extent` variable in `weight.py`, which is then passed to `pointsToVoronoiGridArray` and then to `_get_voronoi_centroid_array` in `voronoi.py`.

The shapefile is available upon request.

**Comment by mgeheran** [comment]
Hello, @AWSisco. Thank you for identifying this issue. Possible solutions include:
1. transforming the catchment shapefile to geographic coordinates beforehand
2. not constraining the LSM data query to the catchment shapefile extents
I added the branch `catchment_extent_warning` to allow the second item. Please let me know if this adequately addresses the issue.

**Comment by AWSisco** [comment]
The `catchment_extent_warning` branch solves my issue. The user is now warned when `clip_to_catchment_shapefile_extent` is `True`, which seems appropriate since we know it can lead to undesired results in at least one circumstance.

Setting `clip_to_catchment_shapefile_extent` to `False` produces the desired weight table for this case, with results very similar to transforming the catchment shapefile to geographic coordinates beforehand (the differences are negligible and can be attributed to the transform occurring within `inflow` versus a desktop GIS).

I recommend this issue be closed upon merging the `catchment_extent_warning` branch.
